apiVersion: v1
kind: Service
metadata:
  name: quarkus-hello-service-app
  labels:
    app: quarkus-hello-service-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: quarkus-hello-service-app
  type: ClusterIP
